### ISSUE TITLE
How do you run it?

### ISSUE THREAD

**Issue by bayleedev** [nelstrom/vimprint#6]
```
-> % pwd
/Users/blaines/vimprint

-> % git rev-parse head
201e3d584992694984b5f918c02b70d3ec0d8ab9

-> % rake
rm -r lib/vimprint/ragel
ragel -R parser.rl -o /Users/blaines/vimprint/lib/vimprint/ragel/parser.rb
/Users/blaines/.rvm/rubies/ruby-2.0.0-p643/bin/ruby -I"lib:test" -I"/Users/blaines/.rvm/gems/ruby-2.0.0-p643/gems/rake-10.0.3/lib" "/Users/blaines/.rvm/gems/ruby-2.0.0-p643/gems/rake-10.0.3/lib/rake/rake_test_loader.rb" "test/vimprint/core_ext/fixnum_test.rb" "test/vimprint/dsl_test.rb" "test/vimprint/formatters/explainer_test.rb" "test/vimprint/model/commands_test.rb" "test/vimprint/model/modes_test.rb" "test/vimprint/model/stage_test.rb" "test/vimprint/ragel/parser_test.rb" "test/vimprint/registry_test.rb" "test/vimprint_test.rb" 
Run options: --seed 21679

# Running:

.....................S.......................................................

Fabulous run in 0.022096s, 3484.7936 runs/s, 4978.2766 assertions/s.

77 runs, 110 assertions, 0 failures, 0 errors, 1 skips

-> % vimprint ~/vimlog
/Users/blaines/vimprint/lib/vimprint/model/modes.rb:29:in `<module:Vimprint>': superclass mismatch for class NormalMode (TypeError)
    from /Users/blaines/vimprint/lib/vimprint/model/modes.rb:1:in `<top (required)>'
    from /Users/blaines/vimprint/lib/vimprint/formatters/explainer.rb:2:in `require'
    from /Users/blaines/vimprint/lib/vimprint/formatters/explainer.rb:2:in `<top (required)>'
    from /Users/blaines/vimprint/lib/vimprint.rb:3:in `require'
    from /Users/blaines/vimprint/lib/vimprint.rb:3:in `<top (required)>'
    from /Users/blaines/vimprint/bin/vimprint:3:in `require'
    from /Users/blaines/vimprint/bin/vimprint:3:in `<top (required)>'
    from /Users/blaines/.rvm/gems/ruby-2.0.0-p643/bin/vimprint:23:in `load'
    from /Users/blaines/.rvm/gems/ruby-2.0.0-p643/bin/vimprint:23:in `<main>'
    from /Users/blaines/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
    from /Users/blaines/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'


-> % ./bin/vimprint ~/vimlog
/Users/blaines/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- vimprint (LoadError)
    from /Users/blaines/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from ./bin/vimprint:3:in `<main>'
```

**Comment by bayleedev** [comment]
Using it as a gem had similar results:

``` ruby
source 'https://rubygems.org'

gem 'vimprint', git: 'git@github.com:nelstrom/vimprint.git'
```

``` ruby
require 'vimprint'

Vimprint.pp('x2x"ax"zx2"ax"a2x3"a2x')
```

```
-> % ruby pp.rb 
/Users/blaines/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- vimprint (LoadError)
    from /Users/blaines/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from pp.rb:1:in `<main>'
```
